"""Base table structure

Revision ID: ed0d99b9bc7c
Revises: 8d02b9c5a131
Create Date: 2024-10-30 00:42:13.139277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0d99b9bc7c'
down_revision: Union[str, None] = '8d02b9c5a131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
